import type { Metadata } from "next";
import { AOSInit } from "../../aos";
import Footer from "../../components/elements/footer";
import Navbar from "../../components/elements/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AOSInit />
      <Navbar />
      {children}
      <Footer />
    </>
  );
}
