name: Required Checks

on:
  push:
    branches: [ main, dev, develop, 'feature/**', 'bugfix/**', 'hotfix/**' ]
  pull_request:
    branches: [ main, dev, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint check with warning tolerance
        run: ./.github/scripts/lint-check.sh

      - name: Type check
        run: bun run type-check

  build-test:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build
