name: Build and Deploy

on:
  push:
    branches: ["main"]
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: ["main"]

jobs:
  build-and-push-dockerfile-image:
    if: startsWith(github.repository, 'Inkubator-IT/template-') == false && (github.event_name == 'push' || github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build application
        run: bun run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/legali-users-fe:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/legali-users-fe:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
